### ISSUE TITLE
Improve the pasting function in tedit

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#16]
Pasting a piece of text from a web page gives strange effects: the font size defined in tedit is not respected, often the pasted text is tiny and sometimes big, the size of the last pasted paragraph applies and changes everything that was before...
At the very least the pasted text does not even respect the size of the original text.
In short, it would be great if you could make the pasting of external elements (mainly texts from web pages) to Tedit more reliable.

**Comment by fulvio999** [comment]
The font size is adjustable from settings menu (gear icon): after the paste you can adjust the font of the pasted text.
Is not possible change font size only for a subset: TextArea (the UBports builtin component, used in the App) don't allow it (i have no control over it, i just use the component and his features as is). Same issue for the Device clipboard, i can't say to it how format his content depending on the source.
To paste text picked-up form a web page you can also use the "Import site as text" features from the menu. But, it import all the text in the web page, not just the selected part as copy & paste.
Sorry but for that reasons the pasting features can't be improved as you expect.
Regards

**Comment by gbdomubpkm** [comment]
Volla phone RC 8 (new qt)
Please check this  : whearas i was testing 'import site as text', it wasn't possible to me to record the new file. In fact the file was probably created but with nothing inside (or visible ?).
I tried again with a simple text file, nothing (visible ?) inside !
Can you confirm me the issue ? 

Edit : i saw indeed that the files created in .local/share/tedit.fulvio are empty (0 bytes).

**Comment by fulvio999** [comment]
Yes, just tested, i confirm the issue about empty files. Also on my Tablet recently switched to "Dev Channel" happen that (on RC channel was Ok).
I suppose the issue is due to recent update of QT library by UBports Dev (i haven't made any updated at Tedit since 2 months..).
I'll try to fix it... but i suppose that solving the issue will have negative effects to the users that still have previous QT version ("stable" channel).
Also on my other App MyPeople i have found some unwanted effects after switch to Dev channel.
In the meantime is better switch/remain to "stable" channel...

**Comment by gbdomubpkm** [comment]
Thanks for the update 👍 Seems to work with OTA-15 too with no negative effects. I close.
