### ISSUE TITLE
[feature request] Be able to bold-fill text elements

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#18]
Without wanting to complicate things too much, this unique formatting option would be useful.

To use either :
- by activating the option
- having previously selected a text, which is currently possible.

**Comment by fulvio999** [comment]
i agree  that is an useful feature (like other ones), but sorry is not possible due to Tedit App is built around the "TextArea" Ubports QML component.
so that Tedit features depends on "TextArea" ones. I mean: if TexArea don't offer it Tedit can't use it.
The original idea of Tedit was have some simple text notes, for advanced feature should be used other text processor available in the Openstore (eg uWriter): the offer that features because are built using other technology like html+javascript components, not almost pure QML like Tedit.
In tedit, the feature about text formatting are only the ones in the settings menu. The are applied to the full text of the note, not at a single part of it.
