### ISSUE TITLE
Incorrect wording of background colors

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#8]
See image of the precedent bug :
The blue background has  green label and the grey background has a blue label

**Comment by fulvio999** [comment]
Sorry but i don't understand. 
The association between label and font colors seems correct. The color gradient used was provide me by an other Tedit user, is not my choice.
The choices of application background color and font color are independent.
So that can happen that with some color combinations (for example Balck font and Blue background) you don't see what you are writing and the user must change on of the colors.
There is no logic to adjust a color based on the other one.
